import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'appbar': 'Language translation',
          'popular': 'Popular',
          'latest': 'Latest',
          'jana gunaso': 'Jana Gunaso',
          'nagarik oda patra': 'Nagarik Oda Patra',
          'palika parichaya': 'Palika Parichaya',
          'nagarik sifaris': 'Nagarik Sifaris',
          'digital munch': 'Digital Munch',
          'aakasmik sewa': 'Aakasmik Sewa',
          'plans': 'Plans',
          'en/kanun': 'En/Kanun',
          'tourist spots': 'Tourist Spots',
          'health check': 'Health Check',
          'education': 'Education',
          'digital profile': 'Digital Profile',
          'karkhana science': 'Karkhana Science',
          'karkhana computer': 'Karkhana Computer',
          'karkhana Make': 'Karkhana Make',
          'science': 'Science',
          'computer': 'Computer',
          'make': 'Make',
          'details': 'Details',
          'location': 'Location',
          'see more': 'See More',
          'view': 'View',
        },
        'ne_nep': {
          'appbar': 'भाषा अनुवाद',
          'popular': 'लोकप्रिय',
          'latest': 'पछिल्लो',
          'jana gunaso': 'जना गुनासो',
          'nagarik oda patra': 'नागरिक ओडा पत्र',
          'palika parichaya': 'पालिका परिचय',
          'nagarik sifaris': 'नागरिक सिफारिस',
          'digital munch': 'डिजिटल मञ्च',
          'aakasmik sewa': 'आकास्मिक सेवा',
          'plans': 'योजनाहरू',
          'en/kanun': 'ऐन/कानून',
          'tourist spots': 'पर्यटकीय स्थल',
          'health check': 'स्वास्थ्य जाँच',
          'education': 'शिक्षा',
          'digital profile': 'डिजिटल प्रोफाइल',
          'karkhana science': 'कारखाना विज्ञान',
          'karkhana computer': 'कारखाना कम्प्युटर',
          'karkhana Make': 'कारखाना बनाउनुहोस्',
          'science': 'विज्ञान',
          'computer': 'कम्प्युटर',
          'make': 'बनाउनुहोस्',
          'details': 'विवरणहरू',
          'location': 'स्थान',
          'see more': 'अझ धेरै हेर्नुहोस्',
          'view': 'हेर्नुहोस्',
        }
      };
}
